### ISSUE TITLE
unexpected post response code: 403 Forbidden

### ISSUE THREAD

**Issue by eyald-ma** [newrelic/newrelic-istio-adapter#33]
Hi,

We are trying to install the new-relic adapter.
and getting 
	error	newrelic	{"err":"unexpected post response code: 403: Forbidden"}

**To Reproduce**
1. Install adapter with:

helm template newrelic-istio-adapter . \                                                                                                                          
    -f values.yaml \
    --namespace istio-system \
    --set authentication.apiKey=<key> \
    --set clusterName=cluster-ci \
    > newrelic-istio-adapter.yaml
kubectl apply -f newrelic-istio-adapter.yaml

2. Get logs from newrelic-istio-adapter pod
error	newrelic	{"err":"unexpected post response code: 403: Forbidden"}

Nothing arrived to new-relic insights

**Version information (please complete the following information):**
 - newrelic-istio-adapter: latest
 - Kubernetes: v1.14
 - Istio: 1.44

**Comment by MrAlias** [comment]
> ...
> --set authentication.apiKey=

Are you actually setting your API key here?

Guessing you are and that was just to not show it here, can you:

* increase the logging level to debug for a service having this issue: https://github.com/newrelic/newrelic-istio-adapter/blob/master/helm-charts/values.yaml#L33-L35
* Look at the logs when the service comes back up
* Ensure they are using a valid API key. It is listed in the New Relic interface as an existing Insights insert key and it the one the logs say is being used (usually near the top of the debug logs)

If that doesn't work, the added verbosity of logging should provided more insight into issues and you can update here with more info (don't forget to sanitize any logs posted).

**Comment by eyald-ma** [comment]
Works now, thanks!
