### ISSUE TITLE
Run as non-root

### ISSUE THREAD

**Issue by MrAlias** [newrelic/newrelic-istio-adapter#9]
Currently the `newrelic-istio-adapter` pods run as the default root user. This configuration is not modifiable and can lead to issues if a cluster has a `podSecurityPolicy` that does not allow this.

Ideally the service can be run as a non-privileged user.

**Comment by mpetruzelli** [comment]
Addressing this with #10

**Comment by mpetruzelli** [comment]
Merged #10
